scl:
  logs:
    - id: 1
      reference: 'pl.k4mil.usageexample.TestBean.createAddress'
      level: warn
      type: before
      message: 'Creating new address - street: {}, city: {}'
      paths:
        - args[0]
        - args[1]

    - id: 2
      reference: 'pl.k4mil.usageexample.TestBean.createPersonWithAddress'
      level: error
      type: after
      message: 'New person created - city: {}, firstName: {}, lastName: {}, id: {}'
      paths:
        - args[2].city
        - args[0]
        - args[1]
        - retVal.id

    - id: 3
      reference: 'pl.k4mil.usageexample.TestBean.createPerson'
      level: info
      type: after
      message: 'New person created - toString(): {}'
      paths:
        - retVal.